kind: pipeline
name: tests-fmt
steps:
  - name: go
    image: golang:1.13
    commands:
      - make test_fmt
trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request
---
kind: pipeline
name: tests-integration
steps:
  - name: wait
    image: golang:1.13
    commands:
      - go run scripts/testutils.go wait
    environment:
      POSTGRES: postgresql://root@pg:5432/core?sslmode=disable
  - name: setup
    image: postgres
    commands:
      - cat postgres/*.sql | psql --host pg --user root --db core
  - name: go
    image: golang:1.13
    commands:
      - make test_integration
    environment:
      POSTGRES: postgresql://root@pg:5432/core?sslmode=disable
services:
  - name: pg
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 
      POSTGRES_DB: core
trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request
---
kind: pipeline
name: tests-unit
steps:
  - name: go
    image: golang:1.13
    commands:
      - make test_unit
trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request
